use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Debug, Deserialize, Serialize, Clone, ToSchema)]
pub struct Currency {
    #[schema(example = "VND")]
    pub currency: &'static str,
    #[schema(example = "₫")]
    pub symbol: &'static str,
    #[schema(example = "Vietnamese Dong")]
    pub english_name: &'static str,
    #[schema(example = "Việt Nam Đồng")]
    pub native_name: &'static str,
}

impl Currency {
    pub const fn new(
        currency: &'static str,
        symbol: &'static str,
        english_name: &'static str,
        native_name: &'static str,
    ) -> Self {
        Currency {
            currency,
            symbol,
            english_name,
            native_name,
        }
    }
}

pub fn validate_currency_code<'a>(code: &'a str) -> Option<&'static Currency> {
    for currency in CURRENCIES {
        if currency.currency == code {
            return Some(currency);
        }
    }

    None
}

pub const CURRENCIES: &'static [Currency] = &[
    Currency::new("AED", "د.إ", "United Arab Emirates Dirham", "درهم إماراتي"),
    Currency::new("AFN", "؋", "Afghan Afghani", "افغانۍ"),
    Currency::new("ALL", "L", "Albanian Lek", "Leku Shqiptar"),
    Currency::new("AMD", "֏", "Armenian Dram", "դրամ"),
    Currency::new(
        "ANG",
        "ƒ",
        "Netherlands Antillean Guilder",
        "Nederlands-Antilliaanse gulden",
    ),
    Currency::new("AOA", "Kz", "Angolan Kwanza", "Kwanza"),
    Currency::new("ARS", "$", "Argentine Peso", "Peso Argentino"),
    Currency::new("AUD", "$", "Australian Dollar", "Dólar Australiano"),
    Currency::new("AWG", "ƒ", "Aruban Florin", "Arubaanse florin"),
    Currency::new("AZN", "₼", "Azerbaijani Manat", "Azərbaycan manatı"),
    Currency::new(
        "BAM",
        "KM",
        "Bosnia and Herzegovina Convertible Mark",
        "Konvertibilna marka",
    ),
    Currency::new("BBD", "$", "Barbadian Dollar", "Barbadian dollar"),
    Currency::new("BDT", "৳", "Bangladeshi Taka", "টাকা"),
    Currency::new("BGN", "лв", "Bulgarian Lev", "Български лев"),
    Currency::new("BHD", "ب.د", "Bahraini Dinar", "دينار بحريني"),
    Currency::new("BIF", "₣", "Burundian Franc", "Franc burundais"),
    Currency::new("BMD", "$", "Bermudian Dollar", "Bermudian dollar"),
    Currency::new("BND", "$", "Brunei Dollar", "Dolar Brunei"),
    Currency::new("BOB", "Bs.", "Bolivian Boliviano", "Boliviano"),
    Currency::new("BRL", "R$", "Brazilian Real", "Real brasileiro"),
    Currency::new("BSD", "$", "Bahamian Dollar", "Bahamian dollar"),
    Currency::new("BTN", "Nu.", "Bhutanese Ngultrum", "དངུལ་ཀྲམ"),
    Currency::new("BWP", "P", "Botswana Pula", "Pula ya Botswana"),
    Currency::new("BYN", "Br", "Belarusian Ruble", "Беларускі рубель"),
    Currency::new(
        "BYR",
        "Br",
        "Belarusian Ruble (pre-2016)",
        "Беларускі рубель",
    ),
    Currency::new("BZD", "$", "Belize Dollar", "Belize dollar"),
    Currency::new("CAD", "$", "Canadian Dollar", "Dollar Canadiense"),
    Currency::new("CDF", "FC", "Congolese Franc", "Franc congolais"),
    Currency::new("CHF", "CHF", "Swiss Franc", "Schweizer Franken"),
    Currency::new(
        "CLF",
        "UF",
        "Chilean Unit of Account (UF)",
        "Unidad de Fomento",
    ),
    Currency::new("CLP", "$", "Chilean Peso", "Peso Chileno"),
    Currency::new("CNY", "¥", "Chinese Yuan", "人民币"),
    Currency::new("COP", "$", "Colombian Peso", "Peso Colombiano"),
    Currency::new("CRC", "₡", "Costa Rican Colón", "Colón Costarricense"),
    Currency::new(
        "CUC",
        "$",
        "Cuban Convertible Peso",
        "Peso Cubano Convertible",
    ),
    Currency::new("CUP", "$", "Cuban Peso", "Peso Cubano"),
    Currency::new("CVE", "$", "Cape Verdean Escudo", "Escudo Caboverdiano"),
    Currency::new("CZK", "Kč", "Czech Koruna", "Česká koruna"),
    Currency::new("DJF", "Fdj", "Djiboutian Franc", "Franc djiboutien"),
    Currency::new("DKK", "kr", "Danish Krone", "Dansk krone"),
    Currency::new("DOP", "RD$", "Dominican Peso", "Peso Dominicano"),
    Currency::new("DZD", "د.ج", "Algerian Dinar", "دينار جزائري"),
    Currency::new("EGP", "ج.م", "Egyptian Pound", "جنيه مصري"),
    Currency::new("ERN", "Nfk", "Eritrean Nakfa", "ናቕፋ"),
    Currency::new("ETB", "Br", "Ethiopian Birr", "ብር"),
    Currency::new("EUR", "€", "Euro", "Euro"),
    Currency::new("FJD", "$", "Fijian Dollar", "Fijian dollar"),
    Currency::new(
        "FKP",
        "£",
        "Falkland Islands Pound",
        "Falkland Islands pound",
    ),
    Currency::new("GBP", "£", "British Pound Sterling", "Pound Sterling"),
    Currency::new("GEL", "₾", "Georgian Lari", "ლარი"),
    Currency::new("GGP", "£", "Guernsey Pound", "Guernsey pound"),
    Currency::new("GHS", "₵", "Ghanaian Cedi", "Ghana Cedi"),
    Currency::new("GIP", "£", "Gibraltar Pound", "Gibraltar pound"),
    Currency::new("GMD", "D", "Gambian Dalasi", "Dalasi"),
    Currency::new("GNF", "FG", "Guinean Franc", "Franc Guinéen"),
    Currency::new("GTQ", "Q", "Guatemalan Quetzal", "Quetzal"),
    Currency::new("GYD", "$", "Guyanese Dollar", "Guyanese dollar"),
    Currency::new("HKD", "$", "Hong Kong Dollar", "港幣"),
    Currency::new("HNL", "L", "Honduran Lempira", "Lempira"),
    Currency::new("HRK", "kn", "Croatian Kuna", "Hrvatska kuna"),
    Currency::new("HTG", "G", "Haitian Gourde", "Gourde"),
    Currency::new("HUF", "Ft", "Hungarian Forint", "Magyar forint"),
    Currency::new("IDR", "Rp", "Indonesian Rupiah", "Rupiah"),
    Currency::new("ILS", "₪", "Israeli New Shekel", "שקל חדש"),
    Currency::new("IMP", "£", "Isle of Man Pound", "Isle of Man pound"),
    Currency::new("INR", "₹", "Indian Rupee", "भारतीय रुपया"),
    Currency::new("IQD", "ع.د", "Iraqi Dinar", "دينار عراقي"),
    Currency::new("IRR", "﷼", "Iranian Rial", "ریال ایران"),
    Currency::new("ISK", "kr", "Icelandic Króna", "Íslensk króna"),
    Currency::new("JEP", "£", "Jersey Pound", "Jersey pound"),
    Currency::new("JMD", "$", "Jamaican Dollar", "Jamaican dollar"),
    Currency::new("JOD", "د.ا", "Jordanian Dinar", "دينار أردني"),
    Currency::new("JPY", "¥", "Japanese Yen", "日本円"),
    Currency::new("KES", "KSh", "Kenyan Shilling", "Shilingi ya Kenya"),
    Currency::new("KGS", "сом", "Kyrgyzstani Som", "сом"),
    Currency::new("KHR", "៛", "Cambodian Riel", "រៀល"),
    Currency::new("KMF", "CF", "Comorian Franc", "Franc Comorien"),
    Currency::new("KPW", "₩", "North Korean Won", "조선민주주의인민공화국 원"),
    Currency::new("KRW", "₩", "South Korean Won", "대한민국 원"),
    Currency::new("KWD", "د.ك", "Kuwaiti Dinar", "دينار كويتي"),
    Currency::new("KYD", "$", "Cayman Islands Dollar", "Cayman Islands dollar"),
    Currency::new("KZT", "₸", "Kazakhstani Tenge", "Қазақстан теңгесі"),
    Currency::new("LAK", "₭", "Lao Kip", "ກີບ"),
    Currency::new("LBP", "ل.ل", "Lebanese Pound", "ليرة لبنانية"),
    Currency::new("LKR", "රු", "Sri Lankan Rupee", "රුපියල්"),
    Currency::new("LRD", "$", "Liberian Dollar", "Liberian dollar"),
    Currency::new("LSL", "L", "Lesotho Loti", "Loti"),
    Currency::new("LTL", "Lt", "Lithuanian Litas", "Litas"),
    Currency::new("LVL", "Ls", "Latvian Lats", "Latvijas lats"),
    Currency::new("LYD", "ل.د", "Libyan Dinar", "دينار ليبي"),
    Currency::new("MAD", "د.م.", "Moroccan Dirham", "درهم مغربي"),
    Currency::new("MDL", "MDL", "Moldovan Leu", "Leu moldovenesc"),
    Currency::new("MGA", "Ar", "Malagasy Ariary", "Ariary"),
    Currency::new("MKD", "ден", "Macedonian Denar", "денар"),
    Currency::new("MMK", "Ks", "Myanmar Kyat", "ကျပ်"),
    Currency::new("MNT", "₮", "Mongolian Tugrik", "Төгрөг"),
    Currency::new("MOP", "MOP$", "Macanese Pataca", "澳門圓"),
    Currency::new("MRO", "UM", "Mauritanian Ouguiya", "Ouguiya"),
    Currency::new("MRU", "UM", "Mauritanian Ouguiya (new)", "Ouguiya"),
    Currency::new("MUR", "₨", "Mauritian Rupee", "roupie mauricienne"),
    Currency::new("MVR", "ރ.", "Maldivian Rufiyaa", "ދިވެހި ރުފިޔާ"),
    Currency::new("MWK", "MK", "Malawian Kwacha", "Kwacha"),
    Currency::new("MXN", "$", "Mexican Peso", "Peso Mexicano"),
    Currency::new("MYR", "RM", "Malaysian Ringgit", "Ringgit Malaysia"),
    Currency::new("MZN", "MT", "Mozambican Metical", "Metical"),
    Currency::new("NAD", "$", "Namibian Dollar", "Namibian dollar"),
    Currency::new("NGN", "₦", "Nigerian Naira", "Naira"),
    Currency::new("NIO", "C$", "Nicaraguan Córdoba", "Córdoba"),
    Currency::new("NOK", "kr", "Norwegian Krone", "Norsk krone"),
    Currency::new("NPR", "₨", "Nepalese Rupee", "नेपाली रूपैयाँ"),
    Currency::new("NZD", "$", "New Zealand Dollar", "New Zealand dollar"),
    Currency::new("OMR", "ر.ع.", "Omani Rial", "ريال عماني"),
    Currency::new("PAB", "B/.", "Panamanian Balboa", "Balboa Panameño"),
    Currency::new("PEN", "S/.", "Peruvian Sol", "Sol peruano"),
    Currency::new("PGK", "K", "Papua New Guinean Kina", "Kina"),
    Currency::new("PHP", "₱", "Philippine Peso", "Piso"),
    Currency::new("PKR", "₨", "Pakistani Rupee", "پاکستانی روپیہ"),
    Currency::new("PLN", "zł", "Polish Zloty", "Złoty"),
    Currency::new("PYG", "₲", "Paraguayan Guarani", "Guaraní"),
    Currency::new("QAR", "ر.ق", "Qatari Riyal", "ريال قطري"),
    Currency::new("RON", "lei", "Romanian Leu", "Leu Românesc"),
    Currency::new("RSD", "дин.", "Serbian Dinar", "Српски динар"),
    Currency::new("RUB", "₽", "Russian Ruble", "Российский рубль"),
    Currency::new("RWF", "FRw", "Rwandan Franc", "Franc rwandais"),
    Currency::new("SAR", "ر.س", "Saudi Riyal", "ريال سعودي"),
    Currency::new(
        "SBD",
        "$",
        "Solomon Islands Dollar",
        "Solomon Islands dollar",
    ),
    Currency::new("SCR", "₨", "Seychellois Rupee", "roupie seychelloise"),
    Currency::new("SDG", "ج.س.", "Sudanese Pound", "جنيه سوداني"),
    Currency::new("SEK", "kr", "Swedish Krona", "Svensk krona"),
    Currency::new("SGD", "$", "Singapore Dollar", "Dolar Singapura"),
    Currency::new("SHP", "£", "Saint Helena Pound", "Saint Helena pound"),
    Currency::new("SLL", "Le", "Sierra Leonean Leone", "Leone"),
    Currency::new("SOS", "S", "Somali Shilling", "Shilin Soomaali"),
    Currency::new("SRD", "$", "Surinamese Dollar", "Surinaamse dollar"),
    Currency::new("STD", "Db", "São Tomé and Príncipe Dobra", "Dobra"),
    Currency::new("STN", "Db", "São Tomé and Príncipe Dobra (new)", "Dobra"),
    Currency::new("SVC", "$", "Salvadoran Colón", "Colón Salvadoreño"),
    Currency::new("SYP", "£", "Syrian Pound", "ليرة سورية"),
    Currency::new("SZL", "E", "Swazi Lilangeni", "Lilangeni"),
    Currency::new("THB", "฿", "Thai Baht", "บาท"),
    Currency::new("TJS", "ЅМ", "Tajikistani Somoni", "сомонӣ"),
    Currency::new("TMT", "m", "Turkmenistan Manat", "Türkmen manady"),
    Currency::new("TND", "د.ت", "Tunisian Dinar", "دينار تونسي"),
    Currency::new("TOP", "T$", "Tongan Pa'anga", "Paʻanga"),
    Currency::new("TRY", "₺", "Turkish Lira", "Türk Lirası"),
    Currency::new(
        "TTD",
        "TT$",
        "Trinidad and Tobago Dollar",
        "Trinidad y Tobago Dólar",
    ),
    Currency::new("TWD", "NT$", "New Taiwan Dollar", "新台幣"),
    Currency::new("TZS", "TSh", "Tanzanian Shilling", "Shilingi ya Tanzania"),
    Currency::new("UAH", "₴", "Ukrainian Hryvnia", "Українська гривня"),
    Currency::new("UGX", "USh", "Ugandan Shilling", "Shillingi ya Uganda"),
    Currency::new("USD", "$", "United States Dollar", "United States dollar"),
    Currency::new("UYU", "$", "Uruguayan Peso", "Peso Uruguayo"),
    Currency::new("UZS", "so'm", "Uzbekistan Som", "O'zbek so'mi"),
    Currency::new("VEF", "Bs.", "Venezuelan Bolívar", "Bolívar"),
    Currency::new(
        "VES",
        "Bs.S",
        "Venezuelan Bolívar Soberano",
        "Bolívar Soberano",
    ),
    Currency::new("VND", "₫", "Vietnamese Dong", "Việt Nam Đồng"),
    Currency::new("VUV", "VT", "Vanuatu Vatu", "Vatu"),
    Currency::new("WST", "WS$", "Samoan Tala", "Tālā"),
    Currency::new("XAF", "FCFA", "Central African CFA Franc", "Franc CFA"),
    Currency::new("XCD", "$", "East Caribbean Dollar", "East Caribbean dollar"),
    Currency::new(
        "XDR",
        "SDR",
        "Special Drawing Rights",
        "Droits de tirage spéciaux",
    ),
    Currency::new("XOF", "CFA", "West African CFA Franc", "Franc CFA"),
    Currency::new("XPF", "₣", "CFP Franc", "Franc Pacifique"),
    Currency::new("YER", "﷼", "Yemeni Rial", "ريال يمني"),
    Currency::new("ZAR", "R", "South African Rand", "Rand"),
    Currency::new("ZMW", "ZK", "Zambian Kwacha", "Kwacha"),
    Currency::new("ZWL", "Z$", "Zimbabwean Dollar", "Dollar"),
];
